import img1 from "../../assets/img2.png";
import img2 from "../../assets/img3.png";
import img3 from "../../assets/img8.jpg";
import img4 from "../../assets/img6.png";

const produtcData = [
  {
    id: 1,
    name: "Margherita Pizza",
    description:
      "Classic pizza with fresh mozzarella, basil, and tomato sauce.",
    price: 899,
    image: img1,
    qty: 1,
  },
  {
    id: 2,
    name: "Cheeseburger",
    description:
      "Juicy beef patty with cheddar cheese, lettuce, tomato, and pickles in a toasted bun.",
    price: 649,
    image: img2,
    qty: 1,
  },
  {
    id: 3,
    name: "Caesar Salad",
    description:
      "Crisp romaine lettuce tossed with Caesar dressing, croutons, and parmesan cheese.",
    price: 559,
    image: img3,
    qty: 1,
  },
  {
    id: 4,
    name: "Chocolate Brownie",
    description:
      "Rich chocolate brownie served with a scoop of vanilla ice cream.",
    price: 375,
    image: img4,
    qty: 1,
  },
  {
    id: 5,
    name: "Veggie Sandwich",
    description: "Fresh vegetables layered in whole wheat bread with mayo.",
    price: 299,
    image: img1,
    qty: 1,
  },
  {
    id: 6,
    name: "Grilled Chicken",
    description: "Tender grilled chicken served with herbs and spices.",
    price: 799,
    image: img2,
    qty: 1,
  },
  {
    id: 7,
    name: "Pasta Alfredo",
    description: "Creamy Alfredo pasta with parmesan and garlic.",
    price: 599,
    image: img3,
    qty: 1,
  },
  {
    id: 8,
    name: "Fruit Salad",
    description: "Fresh seasonal fruits served chilled.",
    price: 349,
    image: img4,
    qty: 1,
  },
  {
    id: 9,
    name: "Paneer Tikka",
    description: "Spicy grilled paneer cubes marinated in Indian spices.",
    price: 499,
    image: img1,
    qty: 1,
  },
  {
    id: 10,
    name: "Chicken Nuggets",
    description: "Crispy golden chicken nuggets served with sauce.",
    price: 399,
    image: img2,
    qty: 1,
  },
  {
    id: 11,
    name: "Veg Burger",
    description: "Vegetable patty with lettuce, tomato, and cheese in a bun.",
    price: 349,
    image: img3,
    qty: 1,
  },
  {
    id: 12,
    name: "Ice Cream Sundae",
    description: "Vanilla ice cream topped with chocolate syrup and nuts.",
    price: 299,
    image: img4,
    qty: 1,
  },
  {
    id: 13,
    name: "Grilled Sandwich",
    description: "Cheese and tomato grilled sandwich with herbs.",
    price: 279,
    image: img1,
    qty: 1,
  },
  {
    id: 14,
    name: "Chicken Wrap",
    description: "Spicy chicken wrapped with fresh vegetables and sauce.",
    price: 499,
    image: img2,
    qty: 1,
  },
  {
    id: 15,
    name: "Mushroom Soup",
    description: "Creamy mushroom soup garnished with parsley.",
    price: 349,
    image: img3,
    qty: 1,
  },
  {
    id: 16,
    name: "Chocolate Muffin",
    description: "Soft and moist chocolate muffin topped with chocolate chips.",
    price: 199,
    image: img4,
    qty: 1,
  },
  {
    id: 17,
    name: "Veg Pizza",
    description: "Delicious pizza with fresh vegetables and mozzarella.",
    price: 699,
    image: img1,
    qty: 1,
  },
  {
    id: 18,
    name: "Fish Fry",
    description: "Spiced and crispy fried fish served with lemon wedges.",
    price: 799,
    image: img2,
    qty: 1,
  },
  {
    id: 19,
    name: "Greek Salad",
    description: "Cucumber, tomato, feta cheese, and olives with dressing.",
    price: 399,
    image: img3,
    qty: 1,
  },
  {
    id: 20,
    name: "Brownie Sundae",
    description: "Warm brownie served with ice cream and chocolate sauce.",
    price: 449,
    image: img4,
    qty: 1,
  },
];

export default produtcData;
